### ISSUE TITLE
can't find zip file 

### ISSUE THREAD

**Issue by soyeonlee-1** [gadsbyfly/PyBioMed#17]
Hello, i want to install the pybiomed, but i can't find the zip file name of download the PyBioMed-1.0.zip.
also https://raw.githubusercontent.com/gadsbyfly/PyBioMed/master/PyBioMed/download/PyBioMed-1.0.zip Not founded

How can i get the pybiomed.zip file?

**Comment by selimcanglr** [comment]
Same for me as well. The provided link responds with 404 Not Found.

**Comment by gadsbyfly** [comment]
thanks for your following.  you can download the package via https://codeload.github.com/gadsbyfly/PyBioMed/zip/refs/heads/master
















At 2022-03-17 03:19:31, "Selim Can Güler" ***@***.***> wrote:

Same for me as well. The provided link responds with 404 Not Found.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
